#ifndef _CTEST_H
#define _CTEST_H

#define PART_NONE				0
#define PART_RESISTOR		1
#define PART_DIODE			2
#define PART_CAPACITOR	3

#define PA11_HIGHZ			GPIOA->CRH &=~ (GPIO_CRH_MODE11 | GPIO_CRH_CNF11_0); GPIOA->CRH |= GPIO_CRH_CNF11_1; GPIOA->BSRR = GPIO_BSRR_BR11
#define PA11_LOW				GPIOA->BSRR = GPIO_BSRR_BR11; GPIOA->CRH &=~ GPIO_CRH_CNF11; GPIOA->CRH |= GPIO_CRH_MODE11
#define PA11_HIGH				GPIOA->BSRR = GPIO_BSRR_BS11; GPIOA->CRH &=~ GPIO_CRH_CNF11; GPIOA->CRH |= GPIO_CRH_MODE11

#define PA10_HIGHZ			GPIOA->CRH &=~ (GPIO_CRH_MODE10 | GPIO_CRH_CNF10_0); GPIOA->CRH |= GPIO_CRH_CNF10_1; GPIOA->BSRR = GPIO_BSRR_BR10
#define PA10_LOW				GPIOA->BSRR = GPIO_BSRR_BR10; GPIOA->CRH &=~ GPIO_CRH_CNF10; GPIOA->CRH |= GPIO_CRH_MODE10
#define PA10_HIGH				GPIOA->BSRR = GPIO_BSRR_BS10; GPIOA->CRH &=~ GPIO_CRH_CNF10; GPIOA->CRH |= GPIO_CRH_MODE10

#define PA9_HIGHZ				GPIOA->CRH &=~ (GPIO_CRH_MODE9 | GPIO_CRH_CNF9_0); GPIOA->CRH |= GPIO_CRH_CNF9_1; GPIOA->BSRR = GPIO_BSRR_BR10
#define PA9_LOW					GPIOA->BSRR = GPIO_BSRR_BR9; GPIOA->CRH &=~ GPIO_CRH_CNF9; GPIOA->CRH |= GPIO_CRH_MODE9
#define PA9_HIGH				GPIOA->BSRR = GPIO_BSRR_BS9; GPIOA->CRH &=~ GPIO_CRH_CNF9; GPIOA->CRH |= GPIO_CRH_MODE9

#define PB13_HIGHZ			GPIOB->CRH &=~ (GPIO_CRH_MODE13 | GPIO_CRH_CNF13_0); GPIOB->CRH |= GPIO_CRH_CNF13_1
#define PB13_LOW				GPIOB->BSRR = GPIO_BSRR_BR13; GPIOB->CRH &=~ GPIO_CRH_CNF13; GPIOB->CRH |= GPIO_CRH_MODE13
#define PB13_HIGH				GPIOB->BSRR = GPIO_BSRR_BS13; GPIOB->CRH &=~ GPIO_CRH_CNF13; GPIOB->CRH |= GPIO_CRH_MODE13

#define PB12_HIGHZ			GPIOB->CRH &=~ (GPIO_CRH_MODE12 | GPIO_CRH_CNF12_0); GPIOB->CRH |= GPIO_CRH_CNF12_1
#define PB12_LOW				GPIOB->BSRR = GPIO_BSRR_BR12; GPIOB->CRH &=~ GPIO_CRH_CNF12; GPIOB->CRH |= GPIO_CRH_MODE12
#define PB12_HIGH				GPIOB->BSRR = GPIO_BSRR_BS12; GPIOB->CRH &=~ GPIO_CRH_CNF12; GPIOB->CRH |= GPIO_CRH_MODE12

#define PB2_HIGHZ				GPIOB->CRL &=~ (GPIO_CRL_MODE2 | GPIO_CRL_CNF2_0); GPIOB->CRL |= GPIO_CRL_CNF2_1
#define PB2_LOW					GPIOB->BSRR = GPIO_BSRR_BR2; GPIOB->CRL &=~ GPIO_CRL_CNF2; GPIOB->CRL |= GPIO_CRL_MODE2
#define PB2_HIGH				GPIOB->BSRR = GPIO_BSRR_BS2; GPIOB->CRL &=~ GPIO_CRL_CNF2; GPIOB->CRL |= GPIO_CRL_MODE2

#define PA5_HIGHZ				GPIOA->CRL &=~ (GPIO_CRL_MODE5 | GPIO_CRL_CNF5_0); GPIOA->CRL |= GPIO_CRL_CNF5_1
#define PA5_ANALOG			GPIOA->CRL &=~ (GPIO_CRL_MODE5 | GPIO_CRL_CNF5)
#define PA5_LOW					GPIOA->BSRR = GPIO_BSRR_BR5; GPIOA->CRL &=~ GPIO_CRL_CNF5; GPIOA->CRL |= GPIO_CRL_MODE5
#define PA5_HIGH				GPIOA->BSRR = GPIO_BSRR_BS5; GPIOA->CRL &=~ GPIO_CRL_CNF5; GPIOA->CRL |= GPIO_CRL_MODE5

#define PA6_HIGHZ				GPIOA->CRL &=~ (GPIO_CRL_MODE6 | GPIO_CRL_CNF6_0); GPIOA->CRL |= GPIO_CRL_CNF6_1
#define PA6_ANALOG			GPIOA->CRL &=~ (GPIO_CRL_MODE6 | GPIO_CRL_CNF6)
#define PA6_LOW					GPIOA->BSRR = GPIO_BSRR_BR6; GPIOA->CRL &=~ GPIO_CRL_CNF6; GPIOA->CRL |= GPIO_CRL_MODE6
#define PA6_HIGH				GPIOA->BSRR = GPIO_BSRR_BS6; GPIOA->CRL &=~ GPIO_CRL_CNF6; GPIOA->CRL |= GPIO_CRL_MODE6

#define PA7_HIGHZ				GPIOA->CRL &=~ (GPIO_CRL_MODE7 | GPIO_CRL_CNF7_0); GPIOA->CRL |= GPIO_CRL_CNF7_1
#define PA7_ANALOG			GPIOA->CRL &=~ (GPIO_CRL_MODE7 | GPIO_CRL_CNF7)
#define PA7_LOW					GPIOA->BSRR = GPIO_BSRR_BR7; GPIOA->CRL &=~ GPIO_CRL_CNF7; GPIOA->CRL |= GPIO_CRL_MODE7
#define PA7_HIGH				GPIOA->BSRR = GPIO_BSRR_BS7; GPIOA->CRL &=~ GPIO_CRL_CNF7; GPIOA->CRL |= GPIO_CRL_MODE7


void testPins(uint8_t pinA, uint8_t pinB);

#endif
